version: '3'


services:
  backend:
    build: ./backend
    restart: always
    environment:
      ISPRODUCTION: True
    volumes:
      - "/srv/kerplunk/:/root/data/"
  
  frontend:
    build: ./frontend
    ports:
      - '8080:80'
    restart: always