version: '3'


services:
  backend:
    build: ./backend
    restart: always
    environment:
      ISPRODUCTION: True
    volumes:
      - "/srv/kerplunk/:/root/data/"
  
  frontend:
    # So, to build the frontend, we'll actually use the multi-stage build in proxy
    # There is a way that we can seperate this but it's a security risk
    # since it will also allow all port traffic on all connected container
    # TLDR: Can't make frontend builder export to a another container without exposing all access
    build: ./frontend
    ports:
      - '443:443'
    restart: always