# syntax=docker/dockerfile:1

FROM python:3.10
ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
WORKDIR /kerplunk
COPY ./backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
WORKDIR /kerplunk/backend/api
EXPOSE 8000
CMD ["python3", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--reload"]
