# syntax=docker/dockerfile:1
   
FROM node as frontend-compiler
WORKDIR /kerplunk
COPY . .
WORKDIR /kerplunk/frontend
RUN npm install && npm run build
FROM python:3.10 as backend-executor
COPY --from=frontend-compiler . .
WORKDIR /kerplunk
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 8000
WORKDIR /kerplunk/backend/api
CMD ["python3", "-m", "uvicorn", "main:app", "--host", "0.0.0.0"]