# syntax=docker/dockerfile:1

FROM python:3.10
WORKDIR /kerplunk
COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
WORKDIR /kerplunk/backend/api
CMD ["python3", "-m", "uvicorn", "main:app", "--host", "0.0.0.0"]